name: specviewenv
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy>=2.0
  - scipy
  - numba
  - matplotlib
  - pyqt=5.15.10
  - opencv
  - spectral
  - pip
  - pip:
      - hylite
      - gfit